version: "3.9"
services:
  what-will-we-eat-services:
    image: "what-will-we-eat-services"
    build:
      context: "."
      dockerfile: ./Dockerfile
    labels:
      traefik.enable: "true" 
      traefik.http.routers.api.rule: "Host(`wwwe-services.local`)"
      traefik.http.routers.api.entrypoints: "http"
    environment:
      DEBUG_MODE: "TRUE"
    networks:
      local-dev:
    volumes:
      - "./dockerFiles/config:/opt/webapps/config/"

networks:
  local-dev:
    name: local-dev
    external: true
