version: "3.9"
services:
  what-will-we-eat-services:
    image: "what-will-we-eat-services"
    build:
      context: "."
      dockerfile: ./Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:localhost;PathPrefix:/services"
      - "traefik.port=8080"
    environment:
      DEBUG_MODE: "TRUE"
    networks:
      local-dev:
    volumes:
      - "./dockerFiles/config:/opt/webapps/config/"

networks:
  local-dev:
